### ISSUE TITLE
Uploading gpx file errors apparently

### ISSUE THREAD

**Issue by saurabhaditya** [jeromecornet/magpx#9]
Steps to replicate:

1. Dowloaded gpx file from https://www.mapmyride.com/routes/view/5780409598/
2. Setup auth as suggested in Readme of this repo
3. Ran command `ruby magpx.rb -g ~/Downloads/route5780409598.gpx`
4. Got error on uturn `Processed 1 file
Processed 2 file
Processed 3 file
Processed 4 file
Processed 5 file
Processed 6 file
Processed 7 file
Unknown maneuver modifier: uturn
no implicit conversion of nil into Hash`

**Comment by jeromecornet** [comment]
Sorry @saurabhaditya I didn't see the issue earlier, but I believe it's fixed now (the route does import for me)
